#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

# ==============================================================================
# Known problems
#
# - VSCode terminal has an integrated shell error code checker using it will
#   cause the {{ .Code }} to always be 0
#   Disable by setting
#     "terminal.integrated.shellIntegration.enabled": false
#   in your settings.json
#   see https://github.com/JanDeDobbeleer/oh-my-posh/discussions/3490
#
# - Bash does not support transient prompt
#   see https://ohmyposh.dev/docs/configuration/transient
#
# - Bash does not support rprompt
#   see https://ohmyposh.dev/docs/configuration/block#type
# ==============================================================================

# Downgrade method:
# curl -s -f -L \
#   https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v23.6.4/posh-linux-amd64 \
#   -o "$HOME/.local/bin/oh-my-posh"

auto_upgrade           = false
console_title_template = '{{ .Shell }} in {{ .Folder }}'
final_space            = true
version                = 3

[palette]
  # https://ohmyposh.dev/docs/configuration/colors
  at_sign_fg = 'white'

  execution_time_bg = 'transparent'
  execution_time_fg = 'red'

  file_path_bg = 'transparent'
  file_path_fg = 'blue'

  git_ahead_fg   = 'green'
  git_behind_fg  = 'red'
  git_bg         = 'transparent'
  git_branch_fg  = 'yellow'
  git_changes_fg = 'red'

  hostname_bg = 'transparent'
  hostname_fg = 'cyan'

  prompt_err_bg = 'transparent'
  prompt_err_fg = 'red'
  prompt_ok_bg  = 'transparent'
  prompt_ok_fg  = 'green'

  python_venv_bg = 'transparent'
  python_venv_fg = 'yellow'

  ssh_session_bg = 'transparent'
  ssh_session_fg = 'red'

  time_bg = 'transparent'
  time_fg = 'green'

  username_bg = 'transparent'
  username_fg = 'magenta'

  wsl_bg = 'transparent'
  wsl_fg = 'red'

# ==============================================================================
# Primary Information line
# ==============================================================================
[[blocks]]
  alignment = 'left'
  type      = 'prompt'

  [[blocks.segments]]
    # https://ohmyposh.dev/docs/segments/system/time
    background = 'p:time_bg'
    foreground = 'p:time_fg'
    style      = 'plain'
    type       = 'time'

    [blocks.segments.properties]
      cache_duration = 'none'
      time_format    = '15:04:05'

  [[blocks.segments]]
    # https://ohmyposh.dev/docs/segments/languages/python
    background = 'p:python_venv_bg'
    foreground = 'p:python_venv_fg'
    style      = 'plain'
    template   = ' {{ .Full }} '
    type       = 'python'

  [[blocks.segments]]
    # https://ohmyposh.dev/docs/segments/system/session
    background = 'p:username_bg'
    foreground = 'p:username_fg'
    style      = 'plain'
    template   = '{{ .UserName }}<p:at_sign_fg>@</>'
    type       = 'session'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    # https://ohmyposh.dev/docs/segments/system/os
    background = 'p:wsl_bg'
    foreground = 'p:wsl_fg'
    style      = 'plain'
    template   = '{{ if .WSL }}WSL<p:at_sign_fg>@</>{{ end }}'
    type       = 'os'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    # https://ohmyposh.dev/docs/segments/system/session
    background = 'p:ssh_session_bg'
    foreground = 'p:ssh_session_fg'
    style      = 'plain'
    template   = '{{ if .SSHSession }}SSH<p:at_sign_fg>@</>{{ end }}'
    type       = 'session'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    # https://ohmyposh.dev/docs/segments/system/session
    background = 'p:hostname_bg'
    foreground = 'p:hostname_fg'
    style      = 'plain'
    template   = '{{ .HostName }}<p:at_sign_fg>:</>'
    type       = 'session'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    # https://ohmyposh.dev/docs/segments/system/path
    background = 'p:file_path_bg'
    foreground = 'p:file_path_fg'
    style      = 'plain'
    template   = '{{ .Path }}'
    type       = 'path'

    [blocks.segments.properties]
      cache_duration = 'none'
      style          = 'full'

  [[blocks.segments]]
    # https://ohmyposh.dev/docs/segments/scm/git
    background = 'p:git_bg'
    foreground = 'p:git_fg'
    style      = 'plain'
    template   = ' <p:git_branch_fg>{{ .HEAD }}</><p:git_changes_fg>{{ if or (.Working.Changed) (.Staging.Changed) }} *{{ end }}</><p:git_behind_fg>{{ if gt .Behind 0 }} ⇣{{ end }}</><p:git_ahead_fg>{{ if gt .Ahead 0 }} ⇡{{ end }}</>'
    type       = 'git'

    [blocks.segments.properties]
      branch_icon    = ' '   # This character is a git branch icon
      cache_duration = 'none'
      fetch_status   = true

  [[blocks.segments]]
    # https://ohmyposh.dev/docs/segments/system/executiontime
    background = 'p:execution_time_bg'
    foreground = 'p:execution_time_fg'
    style      = 'plain'
    template   = ' {{ .FormattedMs }} '
    type       = 'executiontime'

    [blocks.segments.properties]
      always_enabled = false
      cache_duration = 'none'
      style          = 'round'
      threshold      = 5000

# ==============================================================================
# Prompt line
# ==============================================================================
[[blocks]]
  alignment = 'left'
  newline   = true
  type      = 'prompt'

  [[blocks.segments]]
    # https://ohmyposh.dev/docs/segments/system/text
    background_templates = [
      '{{if gt .Code 0}}p:prompt_err_bg{{end}}',
      '{{if eq .Code 0}}p:prompt_ok_bg{{end}}',
    ]
    foreground_templates = [
      '{{if gt .Code 0}}p:prompt_err_fg{{end}}',
      '{{if eq .Code 0}}p:prompt_ok_fg{{end}}',
    ]
    style = 'plain'
    template = '❯'
    type = 'text'

    [blocks.segments.properties]
      cache_duration = 'none'
