#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

console_title_template = '{{ .Shell }} in {{ .Folder }}'
final_space            = true
version                = 2

[[blocks]]
  alignment = 'left'
  type      = 'prompt'

  [[blocks.segments]]
    Duration         = 0
    NameLength       = 0
    Text             = ''
    background       = 'p:yellow'
    foreground       = 'p:black'
    leading_diamond  = ''
    style            = 'diamond'
    template         = ' {{ if .SSHSession }} {{ end }}{{ .UserName }} '
    trailing_diamond = ''
    type             = 'session'

  [[blocks.segments]]
    Duration         = 0
    NameLength       = 0
    Text             = ''
    background       = 'p:orange'
    foreground       = 'p:white'
    powerline_symbol = ''
    style            = 'powerline'
    template         = '  {{ path .Path .Location }} '
    type             = 'path'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    Duration = 0
    NameLength = 0
    Text = ''
    background = 'p:green'
    background_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}',
      '{{ if gt .Ahead 0 }}#49416D{{ end }}',
      '{{ if gt .Behind 0 }}#7A306C{{ end }}',
    ]
    foreground = 'p:black'
    foreground_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}',
      '{{ if gt .Ahead 0 }}p:white{{ end }}',
    ]
    powerline_symbol = ''
    style = 'powerline'
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    type = 'git'

    [blocks.segments.properties]
      branch_max_length   = 25
      fetch_status        = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    Duration         = 0
    NameLength       = 0
    Text             = ''
    background       = 'p:yellow'
    foreground       = 'p:white'
    powerline_symbol = ''
    style            = 'powerline'
    template         = '  '
    type             = 'root'

  [[blocks.segments]]
    Duration             = 0
    NameLength           = 0
    Text                 = ''
    background           = 'p:blue'
    background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
    foreground           = 'p:white'
    leading_diamond      = '<transparent,background></>'
    style                = 'diamond'
    template             = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
    trailing_diamond     = ''
    type                 = 'status'

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    Duration   = 0
    NameLength = 0
    Text       = ''
    background = 'transparent'
    foreground = 'p:green'
    style      = 'plain'
    template   = ' '
    type       = 'node'

    [blocks.segments.properties]
      display_mode          = 'files'
      fetch_package_manager = false
      home_enabled          = false

  [[blocks.segments]]
    Duration   = 0
    NameLength = 0
    Text       = ''
    background = 'transparent'
    foreground = 'p:blue'
    style      = 'plain'
    template   = ' '
    type       = 'go'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    Duration   = 0
    NameLength = 0
    Text       = ''
    background = 'transparent'
    foreground = 'p:yellow'
    style      = 'plain'
    template   = ' '
    type       = 'python'

    [blocks.segments.properties]
      display_mode      = 'files'
      fetch_version     = false
      fetch_virtual_env = false

  [[blocks.segments]]
    Duration   = 0
    NameLength = 0
    Text       = ''
    background = 'transparent'
    foreground = 'p:white'
    style      = 'plain'
    template   = 'in <p:blue><b>{{ .Name }}</b></> '
    type       = 'shell'

  [[blocks.segments]]
    Duration   = 0
    NameLength = 0
    Text       = ''
    background = 'transparent'
    foreground = 'p:white'
    style      = 'plain'
    template   = 'at <p:blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>'
    type       = 'time'

[[tooltips]]
  Duration         = 0
  NameLength       = 0
  Text             = ''
  background       = 'p:orange'
  foreground       = 'p:white'
  leading_diamond  = ''
  style            = 'diamond'
  template         = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
  tips             = ['aws']
  trailing_diamond = ''
  type             = 'aws'

  [tooltips.properties]
    display_default = true

[[tooltips]]
  Duration         = 0
  NameLength       = 0
  Text             = ''
  background       = 'p:blue'
  foreground       = 'p:white'
  leading_diamond  = ''
  style            = 'diamond'
  template         = '  {{ .Name }} '
  tips             = ['az']
  trailing_diamond = ''
  type             = 'az'

  [tooltips.properties]
    display_default = true

[transient_prompt]
  Duration   = 0
  NameLength = 0
  Text       = ''
  background = 'transparent'
  foreground = 'p:black'
  template   = '<p:yellow,transparent></><,p:yellow> {{ .Folder }} </><p:yellow,transparent></> '

[secondary_prompt]
  Duration   = 0
  NameLength = 0
  Text       = ''
  background = 'transparent'
  foreground = 'p:black'
  template   = '<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> '

[palette]
  black  = '#262B44'
  blue   = '#4B95E9'
  green  = '#59C9A5'
  orange = '#F07623'
  red    = '#D81E5B'
  white  = '#E0DEF4'
  yellow = '#F3AE35'
